name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print python version
        run: python3 --version
      - name: Install lint
        run: pip install flake8 black
      - name: Run flake8
        run: flake8 --max-line-length=88 --show-source --statistics .
      - name: Run black
        run: black --check .
