name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Print python version
        run: python --version
      - name: Install pip-tools
        run: pip install pip-tools
      - name: Install python dependencies
        run: pip-compile -o requirements-dev.txt requirements/* && pip-sync -q requirements-dev.txt
      - name: Run ruff version
        run: ruff version
      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format
        run: ruff format --check .
