name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Print python version
        run: python --version
      - name: Install uv
        run: >
          curl -LsSf https://astral.sh/uv/install.sh | sh -q &&
          uv --version
      - name: Hack uv to point venv to Python from setup-python action
        # see https://github.com/astral-sh/uv/issues/1396
        run: echo "VIRTUAL_ENV=${Python_ROOT_DIR}" >> "$GITHUB_ENV"
      - name: Install latest dependencies
        run: >
          uv pip compile -o requirements-dev.txt requirements/* &&
          uv pip sync requirements-dev.txt
      - name: Run shelter version
        run: ./shelter.py --version
      - name: Run ruff version
        run: ruff version
      - name: Run ruff check
        run: ruff check .
      - name: Run ruff format
        run: ruff format --check .
