name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Print python version
        run: python --version
      - name: Install python dependencies
        run: pip install -r requirements.txt
      - name: Install lint
        run: pip install ruff black
      - name: Run ruff
        run: ruff check .
      - name: Run black
        run: black --check .
