name: Image

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  image-build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print python version
        run: python3 --version
      - name: Print make version
        run: make --version
      - name: Run make check
        run: make check
      - name: Login to ghcr
        run: buildah login -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Build image
        run: make image
